### ISSUE TITLE
[REQUEST] BACA PLS BANG

### ISSUE THREAD

**Issue by FatihArridho** [hardianto-cpu/hikki-me#1]
Tambahin topup ml, pubg, dll bang pls. Makasih dah mau baca, kalau bisa di accept request saya bang hehe

**Comment by hardianto-cpu** [comment]
> Tambahin topup ml, pubg, dll bang pls. Makasih dah mau baca, kalau bisa di accept request saya bang hehe

mungkin update nya agak lama

**Comment by YudaXwer** [comment]
> Tambahin topup ml, pubg, dll bang pls. Makasih dah mau baca, kalau bisa di accept request saya bang hehe



> Tambahin topup ml, pubg, dll bang pls. Makasih dah mau baca, kalau bisa di accept request saya bang hehe

Kamu Ini Fatihh

**Comment by YudaXwer** [comment]
> Tambahin topup ml, pubg, dll bang pls. Makasih dah mau baca, kalau bisa di accept request saya bang hehe

Tch

**Comment by hardianto-cpu** [comment]
:)

**Comment by hdiiofficial** [comment]
> 

Dicari aguz bng

**Comment by hardianto-cpu** [comment]
> > 
> 
> Dicari aguz bng

yahaha aguzz

**Comment by FatihArridho** [comment]
> > Tambahin topup ml, pubg, dll bang pls. Makasih dah mau baca, kalau bisa di accept request saya bang hehe
> 
> Tch

Wer tekewer kewer

**Comment by hdiiofficial** [comment]
> 

Cara nambahin di plugins gimana ga paham

**Comment by hardianto-cpu** [comment]
> > 
> 
> Cara nambahin di plugins gimana ga paham

sama aja cuma edit dikit aja udah bisa jadi plugins

**Comment by hdiiofficial** [comment]
> 

masi ga paham

**Comment by hdiiofficial** [comment]
> 

Boleh tu bang kasi contoh plugin

**Comment by hardianto-cpu** [comment]
> > 
> 
> Boleh tu bang kasi contoh plugin

ntr kalo lagi gabut

**Comment by hdiiofficial** [comment]
> 

Gabut dong bang wkwl

**Comment by hardianto-cpu** [comment]
;v

**Comment by hdiiofficial** [comment]
> ;v

Hehe biar uwu bisa anu topup ga perlu ke lain2

**Comment by hardianto-cpu** [comment]
web yg mueah tentunya

**Comment by hdiiofficial** [comment]
> web yg mueah tentunya

Eeeee
